/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Builder: typeof import('./components/Builder.vue')['default']
    ButtonList: typeof import('./components/ButtonList.vue')['default']
    ComponentDrawer: typeof import('./components/layout/ComponentDrawerInner.vue')['default']
    ComponentDrawerInner: typeof import('./components/layout/ComponentDrawerInner.vue')['default']
    ContentToolbar: typeof import('./components/layout/ContentToolbar.vue')['default']
    MainToolbar: typeof import('./components/layout/MainToolbar.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    OptionDrawerInner: typeof import('./components/layout/OptionDrawerInner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
  }
}
